"use client";
import React from "react";
import { BackgroundGradient } from "@/components/ui/background-gradient";
import { IconAppWindow } from "@tabler/icons-react";
import Image from "next/image";

export function BackgroundGradientDemo() {
  return (
    <div>
      <BackgroundGradient className="rounded-[22px] max-w-sm p-4 sm:p-10 bg-gradient-to-br from-slate-300 to-slate-500 ">
        <Image
          src= '/images/OIP (1).jpg'
          width={500}
          height={500}
          priority
          className="h-auto max-w-full rounded-lg" alt=""
          
          
        />
        <p className="text-base sm:text-xl text-black mt-4 mb-2 dark:text-neutral-200">
        Photovoltaic Cells 
        </p>

        <p className="text-sm text-neutral-600 dark:text-neutral-400">
        Solar panels are made up of multiple photovoltaic cells, which are t
        ypically made from silicon. 
        These cells absorb sunlight and convert it into direct 
        current (DC) electricit <br />
        The DC electricity generated by the solar 
        panels is converted into alternating current (AC) 
        electricity by an inverter, making it usable for homes and businesses
        </p>

        <p className="text-base sm:text-xl text-black mt-4 mb-2 dark:text-neutral-200">
        Low Maintenance
        </p>

        <p className="text-sm text-neutral-600 dark:text-neutral-400">
        Once installed, solar panels require minimal maintenance, 
        mainly 
        periodic cleaning and occasional checks <br /> Solar panels provide 
        a clean 
        and renewable source of energy
        </p>
        <button className="rounded-full pl-4 pr-1 py-1 text-white flex items-center space-x-1 bg-black mt-4 text-xs font-bold dark:bg-zinc-800">
          <span>here for you </span>
          <span className="bg-zinc-700 rounded-full text-[0.6rem] px-2 py-0 text-white">
            contact us 
          </span>
        </button>
      </BackgroundGradient>
    </div>
  );
}
